name: Testes e SonarQube Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Build, Testes e Sonar
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Rodar testes e análise no SonarQube Cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B clean verify sonar:sonar
          -Dsonar.projectKey=AlineHAlves-tech_usuario-sonar
          -Dsonar.organization=alinehalves-tech
          -Dsonar.host.url=https://sonarcloud.io
